### ISSUE TITLE
post docker images to dockerhub

### ISSUE THREAD

**Issue by csantanapr** [openwhisk/apigateway#19]
Pulling the source and building the docker image in our travis CI for [openwhisk/openwhisk](https://github.com/openwhisk/openwhisk) takes 7 minutes we don't have large budget to run in travis.
If the repo is link to dockerhub then we can have automated builds, and openwhisk can pull down the image instead of building every time.

Here is more info on linking: 
https://docs.docker.com/docker-hub/github/
https://docs.docker.com/docker-hub/builds/

**Comment by alexsong93** [comment]
The gateway docker image is now hosted on dockerhub: https://hub.docker.com/r/openwhisk/apigateway/ (Thanks Carlos @csantanapr)

By default, it points to the stable `master` branch (ie. `docker run openwhisk/apigateway`). You can also do `docker run openwhisk/apigateway:develop` to test out changes in the `develop` branch.
