### ISSUE TITLE
Gateway is failing with resource timeout

### ISSUE THREAD

**Issue by mhamann** [openwhisk/apigateway#24]
It's not certain what originally caused the failure; however, the gateways are now failing to start due to the following error:

```
Connected to redis at <redacted>

Creating nginx conf files for existing resources...
Updated file: /etc/api-gateway/managed_confs/938b543f-c448-4678-a055-f3d31ed072ae/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/28b8e5fb-8bb6-4390-b22e-c7452c6621f9/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/834e787a-2da3-4334-b3ea-5cd1aa110d83/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/b55902e4-efc4-4986-bfb6-bdc5456a6c55/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/36bc319d-19b8-45b0-9e25-b6cdf14508f9/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/51ba22af-7262-43aa-9da7-4a2efd5c4377/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/11fdaa4a-4112-4489-91ce-107e5ddda799/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/48eb7bc2-fa3f-4285-a4ba-3a308eb94933/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/e3ae65f9-6790-4c6e-b2c0-5a877f2bb551/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/10dbc70b-7d71-4784-9034-762c25173102/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/5e5f4fc1-2052-45d5-8485-963cee087dbd/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/e5bbb84c-177f-4bc7-8412-ce4ba123ce31/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/87cf0221-5705-46f9-b959-7916a364a06d/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/7e5a4116-f785-4637-97a6-bebc54af1c87/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/54c010b2-b19e-482c-b63a-5113e336b4e7/v1%2Fhello.conf
Updated file: /etc/api-gateway/managed_confs/db2318d6-f2f2-41e9-8b1b-88cad7052430/v1%2Fhello.conf
Error: Failed getting resource: timeout
```

Thus, all of the gateways are in a state where they constantly spin up, then shut down (gracefully, it seems).

We should likely look at two things here:
1) What's the root cause?
2) A single bad config (or whatever is causing this) should not be able to bring down the entire gateway.

**Comment by DavidMGreen** [comment]
@mhamann the error is coming from https://github.ibm.com/apimesh/apigateway/blob/baf9744db6fc862c5b155d2440bf08bd05d7013e/api-gateway-config/scripts/lua/lib/redis.lua#L142 and it seems a resource timeout loading (may not exist or may be a corrupt entry), we can expand the error handling to check the err for `timeout` and skip it so the gateway will stay up as a possible fix

**Comment by alexsong93** [comment]
@mhamann Is this error happening on gateway startup? I'm assuming that these 15 or so resources were in redis already?

The gateway is getting an error when trying to get a resource object from redis when it is syncing with redis. My guess is it may have to do with issue https://github.com/openwhisk/apigateway/issues/14, which is blocking redis and causing a timeout error on a subsequent `hget` call.

**Comment by DavidMGreen** [comment]
Yes, Alex is correct that is root cause seems to be https://github.com/openwhisk/apigateway/issues/14
