### ISSUE TITLE
Add x-gateway-host header to response

### ISSUE THREAD

**Issue by lostinthestory** [openwhisk/apigateway#35]
To better debug errors, we should attach an x-gateway-host header to the response of each API call through the gateway. This value will show the IP of the gateway that actually handled the request. This will allow us to quickly determine which gateway instance is having issues if a problem arrises.

**Comment by mhamann** [comment]
Since the primary mechanism for running the gateway is via a Docker container, will such an IP be truly useful? We probably need a way of identifying which container actually served the request, such as the IP/Port combo that points to the running container.

**Comment by lostinthestory** [comment]
Since we're proxying to the ip/port of the container, I wonder what `$server_addr` would yield
