### ISSUE TITLE
Gateway imposes 10k limit on POST body

### ISSUE THREAD

**Issue by starpit** [openwhisk/apigateway#48]
POST bodies to an openwhisk gateway route are squashed for attachments larger than 10 kilobytes. There is no error, the payload is silently squashed. Worse, the entire payload is squashed if any part of it results in the payload as a whole exceeding 10 kilobytes. 

The underlying OpenWhisk action is still invoked, but with an empty payload.

**Comment by DavidMGreen** [comment]
Thank you for bringing this to our attention, we are currently looking into a solution for this.

**Comment by starpit** [comment]
here is a test. if you run `test.sh 5` you get a PASS (exit code 0), and if you run for any value greater than 10*1024, you get FAIL (exit code 1)

[apigwtest.zip](https://github.com/openwhisk/apigateway/files/654972/apigwtest.zip)

**Comment by alexsong93** [comment]
@starpit This was happening because the default in-memory buffer size for nginx is set to just 8K. I've increased the buffer size to 1M to fix the problem.

**Comment by starpit** [comment]
thanks @alexsong93 for the quick fix!!

is the fix in production?

**Comment by starpit** [comment]
has this fix been promoted to production? i'm still seeing the >10k squashing effect. thanks

**Comment by alexsong93** [comment]
@mhamann Have the new changes made its way to the prod/ys1 stacks?
