### ISSUE TITLE
Make policies more pluggable.

### ISSUE THREAD

**Issue by jgeddes2001** [openwhisk/apigateway#52]
Based on https://github.com/openwhisk/apigateway/pull/51#issuecomment-268585064 need to implement make the pre-flow more pluggable. possibly separate out into separate policy repos?

**Comment by taylorking** [comment]
What should this look like? Currently the security block is separate from the policy block. Should I put the security block in the policy block? Should each policy have code in it's own file?

**Comment by taylorking** [comment]
I will pull this out of the oauth work so we can get this in

**Comment by taylorking** [comment]
#69
